# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Kolekto

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Cleaning testing files
        run: |
          cd PKolekto/
          rm db.sqlite3
          rm .env
          cd ..
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            PKolekto
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
  
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: |
            PKolekto
            !venv/
            
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'PKolekto'
          slot-name: 'Production'
          publish-profile: <publishProfile profileName="Kolekto - Web Deploy" publishMethod="MSDeploy" publishUrl="kolekto.scm.azurewebsites.net:443" msdeploySite="Kolekto" userName="$Kolekto" userPWD="XDftrlk4hr4YPg6ytTMljGAvNFMuSn7Rr3fSM2GfWApfSrNsYC6kQpeYM8W0" destinationAppUrl="https://kolekto.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Kolekto - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-cq1-025.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="Kolekto\$Kolekto" userPWD="XDftrlk4hr4YPg6ytTMljGAvNFMuSn7Rr3fSM2GfWApfSrNsYC6kQpeYM8W0" destinationAppUrl="https://kolekto.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="Kolekto - Zip Deploy" publishMethod="ZipDeploy" publishUrl="kolekto.scm.azurewebsites.net:443" userName="$Kolekto" userPWD="XDftrlk4hr4YPg6ytTMljGAvNFMuSn7Rr3fSM2GfWApfSrNsYC6kQpeYM8W0" destinationAppUrl="https://kolekto.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile
